### ISSUE TITLE
Validar

### ISSUE THREAD

**Issue by marcelheinrich** [WallaceRossini/serverless_aws_node#2]
Se tu retornar vazio, vai dar erro no teu service. Pois tu está esperando um objeto data.

Não daria pra melhorar essa validação será? 

https://github.com/WallaceRossini/serverless_aws_node/blob/0e935e416886b830213d817ee5151a4dffefb70b/src/infra/ProductInfra.ts#L16

**Comment by rossiniwallace** [comment]
Validação realizada por statusCode
